CREATE DATABASE Dealer

GO

USE Dealer

GO

CREATE TABLE Marca (
IdMarca INT PRIMARY KEY IDENTITY(1,1),
NombreMarca NVARCHAR(20) NOT NULL
)

GO

CREATE TABLE Provincia (
IdProvincia INT PRIMARY KEY IDENTITY(1,1),
NombreProvincia NVARCHAR(30) NOT NULL
)

GO

CREATE TABLE Ciudad (
IdCiudad INT PRIMARY KEY IDENTITY(1,1),
NombreCiudad NVARCHAR(30) NOT NULL,
IdProvincia INT NOT NULL,
-----LLAVES FORANEAS
CONSTRAINT FK_IdProvincia FOREIGN KEY (IdProvincia) REFERENCES Provincia(IdProvincia)
)

GO

CREATE TABLE Sector (
IdSector INT PRIMARY KEY IDENTITY(1,1),
NombreSector NVARCHAR(30) NOT NULL,
IdCiudad INT NOT NULL,
-----LLAVES FORANEAS
CONSTRAINT FK_IdCiudad FOREIGN KEY (IdCiudad) REFERENCES Ciudad(IdCiudad)
)

GO

CREATE TABLE Modelo (
IdModelo INT PRIMARY KEY IDENTITY(1,1),
NombreModelo NVARCHAR(15) NOT NULL,
IdMarca INT NOT NULL,
-----LLAVES FORANEAS
CONSTRAINT FK_IdMarca FOREIGN KEY (IdMarca) REFERENCES Marca(IdMarca)
)